# Generated by Django 4.0.4 on 2023-02-13 20:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('phone_num', phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, region=None)),
            ],
        ),
        migrations.CreateModel(
            name='Tank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('type', models.CharField(choices=[('Fr', 'Freshwater'), ('Sa', 'Saltwater')], max_length=2)),
                ('volume', models.IntegerField()),
                ('module_id', models.CharField(blank=True, max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.profile')),
            ],
        ),
        migrations.CreateModel(
            name='Parameters',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp_max', models.DecimalField(decimal_places=3, max_digits=7)),
                ('temp_min', models.DecimalField(decimal_places=3, max_digits=7)),
                ('ph_max', models.DecimalField(decimal_places=3, max_digits=7)),
                ('ph_min', models.DecimalField(decimal_places=3, max_digits=7)),
                ('salinity_max', models.DecimalField(decimal_places=3, max_digits=7)),
                ('salinity_min', models.DecimalField(decimal_places=3, max_digits=7)),
                ('ammonia_max', models.DecimalField(decimal_places=3, max_digits=7)),
                ('ammonia_min', models.DecimalField(decimal_places=3, max_digits=7)),
                ('tank', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='hello.tank')),
            ],
        ),
        migrations.CreateModel(
            name='LogData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.IntegerField(choices=[('te', 'temp'), ('ph', 'ph'), ('sa', 'salinity'), ('am', 'ammonia')])),
                ('value', models.DecimalField(decimal_places=3, max_digits=7)),
                ('time_stamp', models.DateTimeField()),
                ('tank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hello.tank')),
            ],
        ),
    ]
