# Generated by Django 4.0.4 on 2023-04-03 17:39

from django.db import migrations, models
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0002_alter_tank_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='logdata',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='email_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_notifications',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='tank',
            name='last_notification_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tank',
            name='send_notifications',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ammonia_max',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ammonia_min',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ph_max',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='ph_min',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='salinity_max',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='salinity_min',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='temp_max',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='parameters',
            name='temp_min',
            field=models.DecimalField(decimal_places=3, default=0.0, max_digits=7),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_num',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
