# Generated by Django 4.1.7 on 2023-04-21 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0004_auto_20230419_1812'),
        ('hello', '0004_parameters_ammonia_enabled_parameters_ph_enabled_and_more'),
    ]

    operations = [
    ]
