# Generated by Django 4.1.5 on 2023-01-24 05:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0005_alter_animal_user_alter_sensor_user_alter_tank_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tank',
            name='sensor',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='hello.sensor'),
            preserve_default=False,
        ),
    ]
