# Generated by Django 4.1.5 on 2023-01-24 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hello', '0007_alter_tank_sensor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tank',
            name='sensor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='hello.sensor'),
        ),
    ]
